package org.jboss.forge.scaffold.faces.metawidget.inspector.propertystyle;

import java.awt.Color;
import java.util.Calendar;
import java.util.Date;

import org.jboss.forge.scaffoldx.metawidget.inspector.propertystyle.NestedMockAnnotation;
import org.jboss.forge.scaffoldx.metawidget.inspector.propertystyle.MockAnnotationSimple;
import org.jboss.forge.scaffoldx.metawidget.inspector.propertystyle.MockAnnotationComplex;
import org.jboss.forge.scaffoldx.metawidget.inspector.propertystyle.MockAnnotationComplex.anEnum;

/**
 * Tests a manually specified class (i.e. not generated by Forge)
 */

public class ManuallyGeneratedClass
{
   //
   // Normal field
   //
   
   private String normalField;
   
   public String getNormalField()
   {
      return this.normalField;
   }

   public void setNormalField(String _normalField)
   {
      this.normalField = _normalField;
   }

   //
   // URL
   //
   
   private String URL;
   
   public String getURL()
   {
      return this.URL;
   }

   public void setURL(String _URL)
   {
      this.URL = _URL;
   }

   //
   // Unusual capitalization: https://issues.jboss.org/browse/FORGEPLUGINS-45
   //

   private String aFIELD;

   public String getaFIELD()
   {
      return this.aFIELD;
   }

   public void setaFIELD(String _aFIELD)
   {
      this.aFIELD = _aFIELD;
   }
}
